"""
src/i18n/fr/backend/strategies.py

Sources and interpretations of calculation strategies.
"""

class StrategySources:
    """
    Descriptions of data sources used in calculations.
    """
    SYSTEM = "SYSTEM_INPUT"
    FORMULA = "Formule Standardisée"
    CAPM_CALC = "Modèle d'Évaluation des Actifs Financiers (MEDAF / CAPM)"
    CALCULATED = "Moteur de calcul interne (Standard Institutionnel)"
    EV_CALC = "Actualisation des flux de trésorerie (NPV) et de la Valeur Terminale"
    WACC_CALC = "Capital Asset Pricing Model (CAPM) & Structure du Capital"
    WACC_TARGET = "Structure Cible"
    WACC_MARKET = "Structure de Marché"
    WACC_FALLBACK = "Structure de Secours (100% Equity)"
    WACC_MANUAL = r"Surcharge manuelle : {wacc:.2%}"
    MANUAL_OVERRIDE = "Manual override (Expert)"
    YAHOO_TTM = "Last reported FCF (TTM) - Yahoo Deep Fetch"
    YAHOO_FUNDAMENTAL = "Fundamental smoothed FCF (Yahoo/Analyst)"
    YAHOO_TTM_SIMPLE = "Yahoo Finance (TTM)"
    CALCULATED_NI = "Calculated (Net Income / Shares)"
    ANALYST_OVERRIDE = "Surcharge Analyste"
    MACRO_MATRIX = r"Matrix: {ticker}"
    MACRO_CURRENCY_FALLBACK = r"Currency Fallback: {ticker}"
    MACRO_STATIC_FALLBACK = "Matrix Static Fallback (API Error)"
    MACRO_API_ERROR = "Matrix Fallback (API Error)"


class StrategyFormulas:
    """
    Standardized LaTeX formulas for all valuation methods.
    """
    GRAHAM_1974 = r"IV = \frac{EPS \times (8.5 + 2g) \times 4.4}{Y_{AAA}}"
    RIM_GLOBAL = r"IV = BV_0 + \sum_{t=1}^{n} \frac{RI_t}{(1+K_e)^t} + \frac{TV}{(1+K_e)^n}"
    RIM_TV = r"TV = \frac{RI_n \times \omega}{1 + K_e - \omega}"
    RIM_RI = r"RI_t = NI_t - (K_e \times BV_{t-1})"
    INTERNAL_CALC = r"\text{Internal Calculation}"
    CAPM = r"K_e = R_f + \beta \times ERP"
    WACC = r"WACC = K_e \times \frac{E}{D+E} + K_d(1-T) \times \frac{D}{D+E}"
    HAMADA = r"\beta_L = \beta_U \times [1 + (1 - T) \times \frac{D}{E}]"
    GORDON = r"TV_n = \frac{FCF_n \times (1 + g_\infty)}{WACC - g_\infty}"
    TERMINAL_MULTIPLE = r"TV_n = FCF_n \times Multiple"
    GROWTH_MARGIN_CONV = r"FCF_t = Rev_t \times [Margin_0 + (Margin_n - Margin_0) \times \frac{t}{n}]"
    FCF_PROJECTION = r"FCF_t = FCF_0 \times (1+g)^t"
    TERMINAL_EXIT_MULTIPLE = r"TV = EBITDA_n \times Multiple"
    FCF_BASE = r"FCF_0"
    REVENUE_BASE = r"Rev_0"
    EPS_BASE = r"EPS"
    BV_BASE = r"BV_0"
    FCF_NORMALIZED = r"FCF_{norm}"
    TRIANGULATION_AVERAGE = r"IV = \frac{\sum Signals}{N}"
    MC_VALID_RATIO = r"\frac{N_{valid}}{N_{total}}"
    MC_MEDIAN = r"Median(IV_i)"
    MC_SENSITIVITY = r"\frac{\partial P50}{\partial \rho}"
    MC_STRESS = r"f(g \to 0, \beta \to 1.5)"
    FCFE_RECONSTRUCTION = r"FCFE = NI + \text{NonCashAdj} + \text{Net Borrowing}"
    FCFE_EQUITY_VALUE = r"\text{Equity Value}"
    DIVIDEND_BASE = r"D_0 \times \text{Shares}"
    FLOW_PROJECTION = r"Flow_t = Flow_{t-1} \times (1+g)"
    PAYOUT_RATIO = r"Payout = \frac{Div_{TTM}}{EPS_{TTM}}"
    RI_SUM = r"\sum_{t=1}^{n} \frac{NI_t - (k_e \times BV_{t-1})}{(1+k_e)^t}"
    RIM_FINAL = r"IV = BV_0 + \sum PV(RI) + PV(TV)"
    NPV = r"PV = \sum_{t=1}^{n} \frac{FCF_t}{(1 + r)^t} + \frac{TV_n}{(1 + r)^n}"
    DCF_STANDARD = r"V_0 = \sum_{t=1}^{n} \frac{FCF_t}{(1+WACC)^t} + \frac{TV_n}{(1+WACC)^n}"
    EQUITY_BRIDGE = r"Equity\ Value = EV - Net\ Debt - Minorities - Pensions + Non\text{-}Op\ Assets"
    VALUE_PER_SHARE = r"IV = \frac{Equity}{Shares\ Outstanding}"
    MC_VOLATILITY_MATRIX = r"\sigma = [\sigma_\beta, \sigma_g, \sigma_{Y_0}]"
    PE_MULTIPLE = r"P/E = \frac{Price}{EPS}"
    EV_EBITDA_MULTIPLE = r"EV/EBITDA = \frac{Enterprise\ Value}{EBITDA}"
    PRICE_FROM_PE = r"Price_{P/E} = \frac{Net\ Income \times Median\ P/E}{Shares}"
    PRICE_FROM_EV_EBITDA = r"Price_{EV/EBITDA} = \frac{EBITDA \times Median\ EV/EBITDA - Debt + Cash}{Shares}"
    RIM_RESIDUAL_INCOME = r"RI_t = NI_t - (K_e \times BV_{t-1})"
    RIM_PERSISTENCE = r"TV_{RI} = \frac{RI_n \times \omega}{1 + k_e - \omega}"
    GRAHAM_MULTIPLIER = r"M = 8.5 + 2g"
    GRAHAM_VALUE = r"IV = \frac{EPS \times (8.5 + 2g) \times 4.4}{Y}"
    AUDIT_BORROWING = r"\frac{\text{Net Borrowing}}{\text{NI}} < 0.5"
    AUDIT_SGR = r"g \leq ROE \times (1 - \text{Payout})"
    NA = r"\text{N/A}"
    SBC_DILUTION = r"IV_{adj} = IV \times (1 - \text{SBC Rate})^t"


class StrategyInterpretations:
    """
    Dynamic pedagogical notes generated by strategies (Glass Box).
    """
    RIM_BV_D = "Valeur des capitaux propres par action au début de la projection."
    GRAHAM_INT = "Formule révisée de Benjamin Graham (1974) intégrant le taux sans risque corporate (AAA Yield) comme coût d'opportunité."
    RIM_FINAL = "Agrégation de la Valeur Comptable Initiale, de la Somme des Surplus actualisés et de la Valeur Terminale de persistance."
    RIM_PERSISTENCE = r"Modélisation de la décroissance des surprofits anormaux avec un facteur de persistance Oméga de {val:.2f}."
    RIM_PROJ = r"Projection des Revenus Résiduels (RI) sur {years} ans basée sur la relation Clean Surplus."
    KE_CONTEXT = "Le coût des capitaux propres (Ke) représente le rendement minimum exigé par les actionnaires pour compenser le risque systématique (Bêta) de l'entreprise. Il sert de base au taux d'actualisation des flux futurs."
    EV_CONTEXT = "Représente la valeur intrinsèque de l'outil de production."
    WACC_CONTEXT = "Coût moyen pondéré des sources de financement."
    WACC = r"Taux d'actualisation cible (WACC) de {wacc:.2%}, basé sur la structure de capital actuelle."
    PROJ = r"Projection sur {years} ans à un taux de croissance annuel moyen de {g:.2%}"
    TV = "Estimation de la valeur de l'entreprise au-delà de la période explicite."
    EV = "Valeur totale de l'outil de production actualisée."
    BRIDGE = "Ajustement de la structure financière."
    IV = r"Estimation de la valeur réelle d'une action pour {ticker}."
    HAMADA_ADJUSTMENT_L = "Ajustement du Bêta (Formule de Hamada)"
    HAMADA_ADJUSTMENT_D = "Le risque systématique (Bêta) a été recalculé pour refléter la structure de capital cible (D/E) choisie pour la valorisation."
    RIM_TV = "Estimation de la persistance des surprofits."
    GROWTH_REV = "Point de départ du modèle basé sur le chiffre d'affaires TTM."
    GROWTH_MARGIN = "Modélisation de l'amélioration opérationnelle vers une marge FCF normative."
    GROWTH_TV = "Valeur de l'entreprise à l'infini basée sur la dernière marge convergée."
    GROWTH_EV = "Somme actualisée des flux et de la valeur terminale."
    GROWTH_IV = "Estimation finale du prix théorique par titre."
    FUND_NORM = "Le modèle utilise un flux lisse sur un cycle complet."
    FUND_VIABILITY = "Validation de la capacité à générer des flux positifs sur un cycle."
    GRAHAM_EPS = "Bénéfice par action utilisé comme socle de rentabilité."
    GRAHAM_MULT = "Prime de croissance appliquée selon le barème révisé de Graham."
    GRAHAM_IV = "Estimation de la valeur intrinsèque ajustée par le rendement AAA."
    MC_CLAMP_NOTE = r" (Écrêté de {g_raw:.1%} pour cohérence WACC)"
    MC_INIT = r"Calibration des lois normales multivariées.{note}"
    MC_SAMPLING_SUB = r"Génération de {count} vecteurs d'inputs via Décomposition de Cholesky."
    MC_SAMPLING_INTERP = "Application des corrélations pour garantir la cohérence économique."
    MC_FILTERING = "Élimination des scénarios de divergence pour stabiliser la distribution."
    MC_SENS_NEUTRAL = "Neutre (rho=0)"
    MC_SENS_BASE = "Base (rho=-0.3)"
    MC_SENS_INTERP = "Audit de l'impact de la corrélation sur la stabilité."
    MC_STRESS_SUB = r"Bear Case = {val:,.2f} {curr}"
    MC_STRESS_INTERP = "Scénario de stress : croissance nulle et risque élevé."
    FCFE_LOGIC = "Le modèle FCFE valorise les fonds propres après service de la dette."
    DDM_LOGIC = "Le modèle DDM repose sur la distribution future."
    RELATIVE_PE = r"Valeur basée sur le multiple P/E médian du secteur ({val:.1f}x)."
    RELATIVE_EBITDA = r"Valeur basée sur le multiple EV/EBITDA médian ({val:.1f}x)."
    TRIANGULATION_SUB = r"Moyenne de {count} signaux valides"
    TRIANGULATION_FINAL = "Valeur hybride obtenue par la moyenne des méthodes relatives."
    SBC_DILUTION_INTERP = r"La dilution annuelle (SBC) réduit la part des actionnaires existants de {pct} sur l'horizon de projection."


class SharedTexts:
    """
    SOCLE COMMUN - Centralise l'intégralité des labels, messages et formules
    utilisés par les terminaux experts et les widgets de saisie.
    Version : Finance de Marché (Institutionnel)
    """

    # ==========================================================================
    # 1. INPUTS GÉNÉRIQUES (WIDGETS PARTAGÉS)
    # ==========================================================================
    HELP_MANUAL_PEERS = "Saisir les codes tickers (ex: AAPL, MSFT) séparés par des virgules pour la triangulation relative."
    HELP_SOTP = "Valorisation par addition des segments opérationnels distincts (Business Units) moins la dette nette globale."
    HELP_SCENARIO_ENABLE = "Permet de modéliser trois trajectoires (Pessimiste, Base, Optimiste) pondérées par probabilité."
    PLACEHOLDER_PEERS = "ex: AAPL, MSFT, GOOGL, LVMH"
    HELP_PEER_TRIANGULATION = "Comparaison de la valeur intrinsèque calculée face aux multiples médians d'un panier de comparables."
    HELP_BACKTEST_ENABLE = "Exécution rétrospective du modèle sur les exercices passés pour valider sa capacité prédictive."
    HELP_MC_VOL_GN = "Écart-type appliqué au taux de croissance perpétuelle dans la simulation."
    HELP_MC_VOL_BETA = "Incertitude statistique sur le risque systématique (Bêta) du titre."
    HELP_MC_VOL_G = "Volatilité du taux de croissance (CAGR) sur la période explicite."
    HELP_MC_VOL_FLOW = "Incertitude sur le flux de trésorerie initial (Année 0) ou normatif."
    HELP_MC_ENABLE = "Simulation stochastique (Monte Carlo) pour définir un intervalle de confiance sur la valorisation."
    HELP_CASH = "Trésorerie active, équivalents de trésorerie et placements financiers liquides."
    HELP_DEBT = "Dette financière brute (bancaire et obligataire), incluant la part courante et les baux (IFRS 16)."
    HELP_SHARES = "Nombre total d'actions diluées (incluant les options exercibles et RSUs)."
    HELP_TAX = "Taux d'imposition effectif moyen projeté sur la période."
    HELP_KD = "Coût de la dette marginal avant économie d'impôt."
    HELP_MRP = "Prime de risque de marché (Equity Risk Premium) historique ou implicite."
    HELP_BETA = "Sensibilité du titre aux mouvements du marché (Bêta leveragé)."
    HELP_RF = "Rendement des obligations d'État à 10 ans (référence 'sans risque')."
    LBL_SEGMENT_METHOD = "Méthode"
    LBL_SEGMENT_VALUE = "Valeur (M$)"
    LBL_SEGMENT_NAME = "Business Unit"
    DEFAULT_SEGMENT_NAME = "Cœur de Métier"
    LBL_VOL_GN = "Volatilité Croissance Infinie (σ)"
    HELP_MC_SIMS = "Nombre de tirages aléatoires (simulations). Recommandé : > 5000 pour la convergence."
    HELP_SENS_RANGE = "Nombre de pas de variation testés au-dessus et en dessous de la valeur centrale."
    LBL_SENS_RANGE = "Portée (Range)"
    HELP_SENS_STEP = "Incrément de variation pour chaque pas (ex: 0.5%)."
    LBL_SENS_STEP = "Pas de variation (%)"
    MSG_SENSITIVITY_DESC = "Analyse croisée de l'impact des variations du WACC et de la Croissance terminale (g) sur la valorisation."
    LBL_SENSITIVITY_ENABLE = "Activer l'Analyse de Sensibilité"
    SEC_11_SENSITIVITY = "#### Extension : Analyse de Sensibilité"
    HELP_SBC_DILUTION = "Taux de dilution annuel estimé lié aux plans de rémunération en actions (Stock-Based Compensation)."
    HELP_EXIT_MULT = "Multiple d'EBITDA ou de CA appliqué à la dernière année de projection pour la Valeur Terminale."
    HELP_PERP_G = "Taux de croissance à l'infini (doit être inférieur au PIB nominal pour la cohérence économique)."

    INP_PROJ_YEARS = "Années de projection (Horizon explicite)"
    HELP_PROJ_YEARS = "Durée de la période de prévision explicite avant calcul de la Valeur Terminale (généralement 5 à 10 ans)."

    INP_GROWTH_G = "Croissance perpétuelle (g)"
    HELP_GROWTH_RATE = "Taux de croissance à l'infini (borné par le taux sans risque pour cohérence économique)."

    INP_PERP_G = "Croissance perpétuelle (g)"

    INP_SHARES = "Actions en circulation (Millions)"

    INP_OMEGA = "Facteur de Persistance (ω)"
    HELP_OMEGA = "Détermine la vitesse à laquelle le rendement excédentaire (ROIC - WACC) converge vers zéro (Modèle Ohlson)."

    # ==========================================================================
    # 2. SECTION ACTUALISATION (DISCOUNT RATES)
    # ==========================================================================
    SEC_3_CAPITAL = "#### Étape 3 : Coût du Capital & Risque"
    SEC_3_DESC = "Définition des paramètres d'actualisation (WACC/Ke) et de la structure du capital cible."

    LBL_DISCOUNT = "Paramètres d'Actualisation"

    # Inputs Taux
    INP_RF = "Taux Sans Risque (Rf)"
    INP_BETA = "Bêta du Titre (β)"
    INP_MRP = "Prime de Risque Marché (ERP)"
    INP_KD = "Coût de la Dette avant impôt (Kd)"
    INP_TAX = "Taux d'Imposition Effectif (Tax)"

    # Structure Capital
    INP_PRICE_WEIGHTS = "Pondération de la Dette (%)"
    HELP_PRICE_WEIGHTS = "Ratio Dette Nette / (Dette Nette + Capitalisation). Si 0, structure 100% Equity."

    # Formules (LaTeX)
    FORMULA_CAPITAL_KE = r"K_e = R_f + \beta \times (R_m - R_f)"
    FORMULA_CAPITAL_WACC = r"WACC = K_e \times \frac{E}{D+E} + K_d(1-T) \times \frac{D}{D+E}"

    # ==========================================================================
    # 3. SECTION VALEUR TERMINALE (TERMINAL VALUE)
    # ==========================================================================
    SEC_4_TERMINAL = "#### Étape 4 : Valeur Terminale (TV)"
    SEC_4_DESC = "Méthodologie de calcul de la valeur au-delà de l'horizon explicite."

    RADIO_TV_METHOD = "Méthode de Sortie"
    TV_GORDON = "Croissance Perpétuelle (Gordon-Shapiro)"
    TV_EXIT = "Multiple de Sortie (Exit Multiple)"

    INP_EXIT_MULT = "Multiple de Sortie (x)"

    # Formules TV (LaTeX) - Spécifiques par modèle
    FORMULA_TV_GORDON = r"TV_n = \frac{Flow_{n+1}}{r - g}"
    FORMULA_TV_EXIT = r"TV_n = Metric_n \times Multiple"

    FORMULA_TV_FCFF_STD = r"TV_n = \frac{FCF_n \times (1+g)}{WACC - g}"
    FORMULA_TV_FCFF_NORM = r"TV_n = \frac{FCF_{norm} \times (1+g)}{WACC - g}"
    FORMULA_TV_FCFF_GROWTH = r"TV_n = \frac{Revenue_n \times Margin_{target} \times (1+g)}{WACC - g}"
    FORMULA_TV_FCFE = r"TV_n = \frac{FCFE_n \times (1+g)}{K_e - g}"
    FORMULA_TV_DDM = r"TV_n = \frac{D_n \times (1+g)}{K_e - g}"
    FORMULA_TV_RIM = r"TV_n = \frac{RI_n \times \omega}{1 + k_e - \omega}"

    # ==========================================================================
    # 4. SECTION EQUITY BRIDGE (PONT EV -> EQUITY)
    # ==========================================================================
    SEC_5_BRIDGE = "#### Étape 5 : Pont vers la Valeur des Fonds Propres (Equity Bridge)"
    SEC_5_DESC = "Ajustements du bilan pour passer de la Valeur d'Entreprise (EV) à la Valeur Intrinsèque des actions."

    INP_DEBT = "Dette Financière Totale (M$)"
    INP_CASH = "Trésorerie & Équivalents (M$)"
    INP_MINORITIES = "Intérêts Minoritaires (M$)"
    INP_PENSIONS = "Engagements de Retraite (M$)"
    INP_SBC_DILUTION = "Dilution annuelle SBC (%)"

    # Formules Bridge (LaTeX)
    FORMULA_BRIDGE = r"Equity = EV - \text{Dette Nette} - \text{Intérêts Min.} - \text{Retraites}"
    FORMULA_BRIDGE_SIMPLE = r"Equity = \sum PV(Flux) + PV(TV)"

    # ==========================================================================
    # 5. EXTENSION : MONTE CARLO (RISK)
    # ==========================================================================
    SEC_6_MC = "#### Extension : Simulation Monte Carlo"

    MC_CALIBRATION = "Calibrage des Volatilités (σ)"
    MC_ITERATIONS = "Nombre d'itérations"

    # Labels Volatilité (Inputs)
    MC_VOL_BASE_FLOW = "Volatilité Flux de Base (σ)"
    MC_VOL_G = "Volatilité Croissance (σ)"
    MC_VOL_BETA = "Volatilité Bêta (σ)"
    LBL_VOL_EXIT_M = "Volatilité Multiple Sortie (σ)"

    # Labels Spécifiques (Dynamic Override)
    MC_VOL_EPS = "Volatilité BPA (σ)"  # Graham
    MC_VOL_NI = "Volatilité Résultat Net (σ)"  # RIM
    MC_VOL_DIV = "Volatilité Dividende (σ)"  # DDM

    # ==========================================================================
    # 6. EXTENSION : ANALYSE DE SCÉNARIOS
    # ==========================================================================
    SEC_8_SCENARIOS = "#### Extension : Scénarios Déterministes"
    INP_SCENARIO_ENABLE = "Activer l'Analyse de Scénarios (Bull/Base/Bear)"

    INP_SCENARIO_PROBA = "Probabilité (%)"
    INP_SCENARIO_GROWTH = "Croissance Ajustée (g)"
    INP_SCENARIO_MARGIN = "Marge Cible (%)"

    # ==========================================================================
    # 7. EXTENSION : PEERS (RELATIVE VALUATION)
    # ==========================================================================
    SEC_7_PEERS = "#### Extension : Comparables (Peers)"
    LBL_PEER_ENABLE = "Activer la triangulation par les multiples"
    INP_MANUAL_PEERS = "Liste de tickers manuels (séparés par des virgules)"

    # ==========================================================================
    # 8. EXTENSION : SOTP (SUM OF THE PARTS)
    # ==========================================================================
    SEC_9_SOTP = "#### Extension : Somme des Parties (SOTP)"
    LBL_SOTP_ENABLE = "Activer la décomposition par segments"

    # ==========================================================================
    # 9. EXTENSION : BACKTEST (HISTORICAL)
    # ==========================================================================
    SEC_10_BACKTEST = "#### Extension : Backtesting Historique"
    LBL_BACKTEST_ENABLE = "Activer la validation historique"
    LBL_LOOKBACK = "Profondeur d'analyse (Années)"

    # ==========================================================================
    # 10. EXTENSION : SENSIBILITÉ (HEATMAP)
    # ==========================================================================
    SEC_SENSITIVITY = "#### Extension : Matrice de Sensibilité"
    LBL_SENS_X = "Coût du Capital (WACC/Ke)"
    LBL_SENS_Y = "Croissance Terminale (g)"
    LBL_SENS_SCORE = "Score de Volatilité"
    HELP_SENS_SCORE = "Mesure de la dispersion des valorisations autour du cas central. Un score élevé indique une forte instabilité du modèle."
