"""
core/i18n/fr/backend/strategies.py

Sources and interpretations of calculation strategies.
"""


class StrategySources:
    """
    Descriptions of data sources used in calculations.
    """
    FORMULA = "Formule Standardisée"
    CAPM_CALC = "Modèle d'Évaluation des Actifs Financiers (MEDAF / CAPM)"
    CALCULATED = "Moteur de calcul interne (Standard Institutionnel)"
    EV_CALC = "Actualisation des flux de trésorerie (NPV) et de la Valeur Terminale"
    WACC_CALC = "Capital Asset Pricing Model (CAPM) & Structure du Capital"
    WACC_TARGET = "Structure Cible"
    WACC_MARKET = "Structure de Marché"
    WACC_FALLBACK = "Structure de Secours (100% Equity)"
    WACC_MANUAL = r"Surcharge manuelle : {wacc:.2%}"
    MANUAL_OVERRIDE = "Manual override (Expert)"
    YAHOO_TTM = "Last reported FCF (TTM) - Yahoo Deep Fetch"
    YAHOO_FUNDAMENTAL = "Fundamental smoothed FCF (Yahoo/Analyst)"
    YAHOO_TTM_SIMPLE = "Yahoo Finance (TTM)"
    CALCULATED_NI = "Calculated (Net Income / Shares)"
    ANALYST_OVERRIDE = "Surcharge Analyste"
    MACRO_MATRIX = r"Matrix: {ticker}"
    MACRO_CURRENCY_FALLBACK = r"Currency Fallback: {ticker}"
    MACRO_STATIC_FALLBACK = "Matrix Static Fallback (API Error)"
    MACRO_API_ERROR = "Matrix Fallback (API Error)"


class StrategyFormulas:
    """
    Standardized LaTeX formulas for all valuation methods.
    """

    # === COST OF CAPITAL ===
    GRAHAM_1974 = r"IV = \frac{EPS \times (8.5 + 2g) \times 4.4}{Y_{AAA}}"
    RIM_GLOBAL = r"IV = BV_0 + \sum_{t=1}^{n} \frac{RI_t}{(1+K_e)^t} + \frac{TV}{(1+K_e)^n}"
    RIM_TV = r"TV = \frac{RI_n \times \omega}{1 + K_e - \omega}"
    RIM_RI = r"RI_t = NI_t - (K_e \times BV_{t-1})"
    INTERNAL_CALC = r"\text{Internal Calculation}"
    CAPM = r"K_e = R_f + \beta \times ERP"
    WACC = r"WACC = \frac{V_E}{V_E + V_D} \times K_e + \frac{V_D}{V_E + V_D} \times K_d \times (1 - T_c)"
    HAMADA = r"\beta_L = \beta_U \times [1 + (1 - T) \times \frac{D}{E}]"

    # === TERMINAL VALUE ===
    GORDON = r"TV_n = \frac{FCF_n \times (1 + g_\infty)}{WACC - g_\infty}"
    TERMINAL_MULTIPLE = r"TV_n = FCF_n \times Multiple"

    # === GROWTH MARGIN ===
    GROWTH_MARGIN_CONV = r"FCF_t = Rev_t \times [Margin_0 + (Margin_n - Margin_0) \times \frac{t}{n}]"

    # === PROJECTION ===
    FCF_PROJECTION = r"FCF_t = FCF_0 \times (1+g)^t"

    # === TERMINAL VALUE ===
    TERMINAL_EXIT_MULTIPLE = r"TV = EBITDA_n \times Multiple"

    # === BASE VALUES ===
    FCF_BASE = r"FCF_0"
    REVENUE_BASE = r"Rev_0"
    EPS_BASE = r"EPS"
    BV_BASE = r"BV_0"
    FCF_NORMALIZED = r"FCF_{norm}"

    # === TRIANGULATION ===
    TRIANGULATION_AVERAGE = r"IV = \frac{\sum Signals}{N}"

    # === MONTE CARLO ===
    MC_VALID_RATIO = r"\frac{N_{valid}}{N_{total}}"
    MC_MEDIAN = r"Median(IV_i)"
    MC_SENSITIVITY = r"\frac{\partial P50}{\partial \rho}"
    MC_STRESS = r"f(g \to 0, \beta \to 1.5)"

    # === FCFE ===
    FCFE_RECONSTRUCTION = r"FCFE = NI + \text{NonCashAdj} + \text{Net Borrowing}"
    FCFE_EQUITY_VALUE = r"\text{Equity Value}"

    # === DIVIDEND ===
    DIVIDEND_BASE = r"D_0 \times \text{Shares}"

    # === PROJECTION ===
    FLOW_PROJECTION = r"Flow_t = Flow_{t-1} \times (1+g)"

    # === PAYOUT ===
    PAYOUT_RATIO = r"Payout = \frac{Div_{TTM}}{EPS_{TTM}}"

    # === SUM RI ===
    RI_SUM = r"\sum_{t=1}^{n} \frac{NI_t - (k_e \times BV_{t-1})}{(1+k_e)^t}"

    # === FINAL VALUES ===
    RIM_FINAL = r"IV = BV_0 + \sum PV(RI) + PV(TV)"

    # === NET PRESENT VALUE ===
    NPV = r"PV = \sum_{t=1}^{n} \frac{FCF_t}{(1 + r)^t} + \frac{TV_n}{(1 + r)^n}"

    # === DCF STANDARD (ST-2.2) ===
    DCF_STANDARD = r"V_0 = \sum_{t=1}^{n} \frac{FCF_t}{(1+WACC)^t} + \frac{TV_n}{(1+WACC)^n}"

    # === OTHER FORMULAS ===
    EQUITY_BRIDGE = r"Equity = EV - Debt + Cash - Minority - Provisions"
    VALUE_PER_SHARE = r"IV = \frac{Equity}{Shares\ Outstanding}"

    # === MONTE CARLO ===
    MC_VOLATILITY_MATRIX = r"\sigma = [\sigma_\beta, \sigma_g, \sigma_{Y_0}]"

    # === RELATIVE / MULTIPLES (ST-2.2) ===
    PE_MULTIPLE = r"P/E = \frac{Price}{EPS}"
    EV_EBITDA_MULTIPLE = r"EV/EBITDA = \frac{Enterprise\ Value}{EBITDA}"
    PRICE_FROM_PE = r"Price_{P/E} = \frac{Net\ Income \times Median\ P/E}{Shares}"
    PRICE_FROM_EV_EBITDA = r"Price_{EV/EBITDA} = \frac{EBITDA \times Median\ EV/EBITDA - Debt + Cash}{Shares}"

    # === RIM BANKS ===
    RIM_RESIDUAL_INCOME = r"RI_t = NI_t - (K_e \times BV_{t-1})"
    RIM_PERSISTENCE = r"TV_{RI} = \frac{RI_n \times \omega}{1 + k_e - \omega}"

    # === GRAHAM ===
    GRAHAM_MULTIPLIER = r"M = 8.5 + 2g"
    GRAHAM_VALUE = r"IV = \frac{EPS \times (8.5 + 2g) \times 4.4}{Y}"

    AUDIT_BORROWING = r"\frac{\text{Net Borrowing}}{\text{NI}} < 0.5"
    AUDIT_SGR = r"g \leq ROE \times (1 - \text{Payout})"
    NA = r"\text{N/A}"
    SBC_DILUTION = r"IV_{adj} = IV \times (1 - \text{SBC Rate})^t"


class StrategyInterpretations:
    """
    Dynamic pedagogical notes generated by strategies (Glass Box).
    """

    # DCF & Abstract
    GRAHAM_INT = "Formule révisée de Benjamin Graham (1974) intégrant le taux sans risque corporate (AAA Yield) comme coût d'opportunité."
    RIM_FINAL = "Agrégation de la Valeur Comptable Initiale, de la Somme des Surplus actualisés et de la Valeur Terminale de persistance."
    RIM_PERSISTENCE = r"Modélisation de la décroissance des surprofits anormaux avec un facteur de persistance Oméga de {val:.2f}."
    RIM_PROJ = r"Projection des Revenus Résiduels (RI) sur {years} ans basée sur la relation Clean Surplus."
    KE_CONTEXT = "Le coût des capitaux propres (Ke) représente le rendement minimum exigé par les actionnaires pour compenser le risque systématique (Bêta) de l'entreprise. Il sert de base au taux d'actualisation des flux futurs."
    EV_CONTEXT = "Représente la valeur intrinsèque de l'outil de production."
    WACC_CONTEXT = "Coût moyen pondéré des sources de financement."
    WACC = r"Taux d'actualisation cible (WACC) de {wacc:.2%}, basé sur la structure de capital actuelle."
    PROJ = r"Projection sur {years} ans à un taux de croissance annuel moyen de {g:.2%}"
    TV = "Estimation de la valeur de l'entreprise au-delà de la période explicite."
    EV = "Valeur totale de l'outil de production actualisée."
    BRIDGE = "Ajustement de la structure financière."
    IV = r"Estimation de la valeur réelle d'une action pour {ticker}."
    HAMADA_ADJUSTMENT_L = "Ajustement du Bêta (Formule de Hamada)"
    HAMADA_ADJUSTMENT_D = "Le risque systématique (Bêta) a été recalculé pour refléter la structure de capital cible (D/E) choisie pour la valorisation."

    # RIM
    RIM_TV = "Estimation de la persistance des surprofits."

    # Growth
    GROWTH_REV = "Point de départ du modèle basé sur le chiffre d'affaires TTM."
    GROWTH_MARGIN = "Modélisation de l'amélioration opérationnelle vers une marge FCF normative."
    GROWTH_TV = "Valeur de l'entreprise à l'infini basée sur la dernière marge convergée."
    GROWTH_EV = "Somme actualisée des flux et de la valeur terminale."
    GROWTH_IV = "Estimation finale du prix théorique par titre."

    # Fundamental
    FUND_NORM = "Le modèle utilise un flux lisse sur un cycle complet."
    FUND_VIABILITY = "Validation de la capacité à générer des flux positifs sur un cycle."

    # Graham
    GRAHAM_EPS = "Bénéfice par action utilisé comme socle de rentabilité."
    GRAHAM_MULT = "Prime de croissance appliquée selon le barème révisé de Graham."
    GRAHAM_IV = "Estimation de la valeur intrinsèque ajustée par le rendement AAA."

    # Monte Carlo
    MC_CLAMP_NOTE = r" (Écrêté de {g_raw:.1%} pour cohérence WACC)"
    MC_INIT = r"Calibration des lois normales multivariées.{note}"
    MC_SAMPLING_SUB = r"Génération de {count} vecteurs d'inputs via Décomposition de Cholesky."
    MC_SAMPLING_INTERP = "Application des corrélations pour garantir la cohérence économique."
    MC_FILTERING = "Élimination des scénarios de divergence pour stabiliser la distribution."
    MC_SENS_NEUTRAL = "Neutre (rho=0)"
    MC_SENS_BASE = "Base (rho=-0.3)"
    MC_SENS_INTERP = "Audit de l'impact de la corrélation sur la stabilité."
    MC_STRESS_SUB = r"Bear Case = {val:,.2f} {curr}"
    MC_STRESS_INTERP = "Scénario de stress : croissance nulle et risque élevé."

    FCFE_LOGIC = "Le modèle FCFE valorise les fonds propres après service de la dette."
    DDM_LOGIC = "Le modèle DDM repose sur la distribution future."

    RELATIVE_PE = r"Valeur basée sur le multiple P/E médian du secteur ({val:.1f}x)."
    RELATIVE_EBITDA = r"Valeur basée sur le multiple EV/EBITDA médian ({val:.1f}x)."
    TRIANGULATION_SUB = r"Moyenne de {count} signaux valides"
    TRIANGULATION_FINAL = "Valeur hybride obtenue par la moyenne des méthodes relatives."

    SBC_DILUTION_INTERP = r"La dilution annuelle (SBC) réduit la part des actionnaires existants de {pct} sur l'horizon de projection."